app = "stratify"  # ← replace with your actual Fly.io app name if different

[build]
  buildpacks = ["paketo-buildpacks/python"]

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
