app = "stratify"  # change this to match your Fly.io app name

[build]
  # uses default buildpack unless Dockerfile exists
  buildpacks = ["paketo-buildpacks/python"]
  [build.env]
    BP_PYTHON_VERSION = "3.11.x"


[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
