app = 'stratify-patient-surf-4418'
primary_region = 'dfw'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.redirects]]
    from = "www.stratifyplan.com"
    to = "https://stratifyplan.com"
    status_code = 301

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
